### ISSUE TITLE
Games not visible on external SD Card

### ISSUE THREAD

**Issue by Schattenruf** [ManuelSch81/RG350-EmulationStation_configured#5]
Hi,

I need your help.
I have previously installed rogue firmware and got a new sd card today.
Wanted to set up emulation station but no games are shown on this card.

I formatted it to FAT32 but no chance. The emulators show up just fine on the RG350 explorer but the games are all "gone". With WINSCP I can see them but not on the device itself.

Any ideas?

Thanks :)

**Comment by Schattenruf** [comment]
To be more precise:

Nintendo GBA is filled with Roms: Can't see any.
Sony Playstation has one ROM: I can see it but no emulator is shown in emulation station.

**Comment by ManuelSch81** [comment]
Hi Schattenruf,
just read your mail. So ist your problem solved or do you need any further help on this?

 

Cheers,

Manuel

 

Von: Schattenruf <notifications@github.com> 
Gesendet: Freitag, 28. Februar 2020 20:53
An: ManuelSch81/RG350-EmulationStation_configured <RG350-EmulationStation_configured@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [ManuelSch81/RG350-EmulationStation_configured] Games not visible on external SD Card (#5)

 

Oh I seemed to have figured it out... I depends on the spaces in the file names...

**Comment by Schattenruf** [comment]
Further help ;) (see above)

**Comment by Schattenruf** [comment]
Edit: I can see the files in DinguxCmdr and not in Explorer but (as mentioned above) emulation station does not show them either

**Comment by ManuelSch81** [comment]
Ok, what is the file extension of your gba roms?
Ensure your roms extensions are listed int he es_systems.cfg file under
<extension>.zip, .gba</extension>

Also check that the path to your rom folder is correct (depends on the name of your sd-card)
<path>/media/RG-350/roms/Gameboy Advance</path>
Same with the path to your emulator:	
<command>"opkrun" "/media/RG-350/emulators/regba.opk" %ROM%</command>

Check this and let me know if you succeeded.

**Comment by Schattenruf** [comment]
Mhhh maybe I have found it? In media I just have the folder sdcard not RG-350
On windows I renamed correctly... But I cannot rename it

**Comment by ManuelSch81** [comment]
yes, you have to take the name that is shown in dinguxcommander ;) that's how it's labeled in your system.
This is a known "problem" with Rogue firmware. It ignores the name of the sd-card and replaces it with "sdcard". I'm pretty sure that's it ;)

**Comment by Schattenruf** [comment]
Ah ok. I test it out.

**Comment by Schattenruf** [comment]
Functions ;) Ok maybe you should add that to the front page for other ROGUE-Users like me

**Comment by ManuelSch81** [comment]
Ok, i'm glad this is resolved.
Yea, i made the description for the stable versions 1.5 and 1.7. Rogue firmware is experimental (not a stable release) so i don't have it installed to my RG350 and so don't have any experiences with it. All i know is from the feedback i get.
So thanks for mentioning.

**Comment by Schattenruf** [comment]
NP ;)

Offtopic: Do you know how I can set a hotkey for GPSP?
Can't seem to quit Playstation Games...

**Comment by Schattenruf** [comment]
Edit: Seems to be that SELECT + START don't work in any emulator as a hotkey. Any ideas?

**Comment by ManuelSch81** [comment]
Try the Power-Button or press both Shoulder Buttons at the same time.

**Comment by Schattenruf** [comment]
Ah Power does it 👍
